INSERT OR IGNORE INTO shops (
  slug,
  name,
  name_kana,
  area,
  address,
  hours,
  holiday,
  instagram,
  genre,
  features,
  description,
  budget_min,
  budget_max,
  seats,
  phone,
  is_recruiting,
  is_published
) VALUES (
  'darts-bar-ark',
  'darts&bar ark（アーク）',
  'アーク',
  '熊本市',
  '熊本市中央区安政町6-3 TM11ビル9F',
  '21:00〜LAST',
  '不定休',
  'https://www.instagram.com/dartsbarark',
  'ダーツバー',
  '一人飲み,デート向け,深夜営業,飲み放題あり,喫煙可',
  '熊本・安政町にある、初心者から経験者まで気軽に楽しめるアットホームなダーツバー。おひとり様やダーツ初心者も歓迎。ハウストーナメントや各種イベントも開催。',
  3000,
  5000,
  18,
  NULL,
  0,
  1
);
